### ISSUE TITLE
missing port USPCV

### ISSUE THREAD

**Issue by federgilad** [marchah/sea-ports#5]
Hey, this json work is amazing. This one port is missing. 
might do a pull request later if I find the time :)

**Comment by marchah** [comment]
Hi,

Let me know what you think:

https://github.com/marchah/sea-ports/pull/6

**Comment by federgilad** [comment]
hey! thanks for creating a PR. I commented there that I believe it's in Antwerp, Belgium.

I might add a few extra pull requests in the future as I use this json in production and alert myself when I catch a port that is not described.

**Comment by deanthedream** [comment]
The World Port Index should have a baseline level of data available for all ports https://msi.nga.mil/Publications/WPI This is a very interesting and useful git repo. Thank you for your time and effort developing it.
